//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TetrisEngine.AzureDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class HighScore
    {
        public int LogID { get; set; }
        public string PlayerName { get; set; }
        public int Score { get; set; }
        public System.DateTime timeStamp { get; set; }
    }
}
